# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T07:44:07+00:00

from __future__ import annotations

from typing import Any, Dict, List, Optional

from pydantic import BaseModel


class Debug(BaseModel):
    version: Optional[float] = None


class Comment(BaseModel):
    approveDate: Optional[str] = None
    assetID: Optional[int] = None
    assetURL: Optional[str] = None
    commentBody: Optional[str] = None
    commentID: Optional[int] = None
    commentSequence: Optional[int] = None
    commentTitle: Optional[str] = None
    commentType: Optional[str] = None
    createDate: Optional[str] = None
    editorsSelection: Optional[int] = None
    lft: Optional[int] = None
    parentID: Optional[Any] = None
    recommendationCount: Optional[int] = None
    replies: Optional[List[Dict[str, Any]]] = None
    replyCount: Optional[int] = None
    rgt: Optional[int] = None
    status: Optional[str] = None
    statusID: Optional[int] = None
    updateDate: Optional[str] = None
    userDisplayName: Optional[str] = None
    userID: Optional[int] = None
    userLocation: Optional[str] = None
    userTitle: Optional[str] = None
    userURL: Optional[int] = None


class Results(BaseModel):
    api_timestamp: Optional[str] = None
    comments: Optional[List[Comment]] = None
    totalCommentsFound: Optional[int] = None
    totalCommentsReturned: Optional[int] = None


class JsonGetResponse(BaseModel):
    copyright: Optional[str] = None
    debug: Optional[Debug] = None
    results: Optional[Results] = None
    status: Optional[str] = None
