# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T07:44:07+00:00

from __future__ import annotations

from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


class Debug(BaseModel):
    version: Optional[float] = None


class AllProperty(BaseModel):
    description: Optional[str] = None
    name: Optional[str] = None
    properties: Optional[List[Dict[str, Any]]] = None


class Label(BaseModel):
    labelID: Optional[int] = None
    labelName: Optional[str] = None


class AutomoderationOff(BaseModel):
    groupID: Optional[int] = None
    taxonomyID: Optional[int] = None


class CommentListSortApprovedateDesc(BaseModel):
    groupID: Optional[int] = None
    taxonomyID: Optional[int] = None


class ReachedMaxComOn(BaseModel):
    groupID: Optional[int] = None
    taxonomyID: Optional[int] = None


class Properties(BaseModel):
    automoderation_off: Optional[AutomoderationOff] = Field(
        None, alias='automoderation-off'
    )
    comment_list_sort_approvedate_desc: Optional[CommentListSortApprovedateDesc] = (
        Field(None, alias='comment-list-sort-approvedate-desc')
    )
    reached_max_com_on: Optional[ReachedMaxComOn] = Field(
        None, alias='reached-max-com-on'
    )


class Asset(BaseModel):
    all_properties: Optional[List[AllProperty]] = Field(None, alias='all-properties')
    assetID: Optional[int] = None
    assetTitle: Optional[str] = None
    assetURL: Optional[str] = None
    createDate: Optional[str] = None
    labels: Optional[List[Label]] = None
    properties: Optional[Properties] = None
    source: Optional[str] = None
    taxonomy: Optional[str] = None
    text: Optional[List[Dict[str, Any]]] = None
    updateDate: Optional[str] = None
    vendorID: Optional[str] = None


class Comment(BaseModel):
    approveDate: Optional[str] = None
    asset: Optional[Asset] = None
    commentBody: Optional[str] = None
    commentID: Optional[int] = None
    commentSequence: Optional[int] = None
    commentTitle: Optional[str] = None
    commentType: Optional[str] = None
    createDate: Optional[str] = None
    editorsSelection: Optional[bool] = None
    labels: Optional[List[Dict[str, Any]]] = None
    parentID: Optional[Any] = None
    permid: Optional[int] = None
    picURL: Optional[str] = None
    recommendations: Optional[int] = None
    replies: Optional[List[Dict[str, Any]]] = None
    replyCount: Optional[int] = None
    status: Optional[str] = None
    updateDate: Optional[str] = None
    userDisplayName: Optional[Any] = None
    userID: Optional[int] = None
    userLocation: Optional[Any] = None
    userSubmittedDisplayName: Optional[str] = None
    userSubmittedLocation: Optional[str] = None
    userSubmittedTitle: Optional[Any] = None
    userSubmittedURL: Optional[Any] = None
    userTitle: Optional[Any] = None
    userURL: Optional[Any] = None


class Results(BaseModel):
    api_timestamp: Optional[str] = None
    comments: Optional[List[Comment]] = None
    totalCommentsFound: Optional[int] = None
    totalCommentsReturned: Optional[int] = None


class JsonGetResponse(BaseModel):
    copyright: Optional[str] = None
    debug: Optional[Debug] = None
    results: Optional[Results] = None
    status: Optional[str] = None
