# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T07:44:07+00:00

from __future__ import annotations

from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


class Debug(BaseModel):
    version: Optional[float] = None


class AllProperty(BaseModel):
    description: Optional[str] = None
    name: Optional[str] = None
    properties: Optional[List[Dict[str, Any]]] = None


class AutomoderationOn(BaseModel):
    groupID: Optional[int] = None
    taxonomyID: Optional[int] = None


class CommentListSortEditors(BaseModel):
    groupID: Optional[int] = None
    taxonomyID: Optional[int] = None


class ReachedMaxComOff(BaseModel):
    groupID: Optional[int] = None
    taxonomyID: Optional[int] = None


class Properties(BaseModel):
    automoderation_on: Optional[AutomoderationOn] = Field(
        None, alias='automoderation-on'
    )
    comment_list_sort_editors: Optional[CommentListSortEditors] = Field(
        None, alias='comment-list-sort-editors'
    )
    reached_max_com_off: Optional[ReachedMaxComOff] = Field(
        None, alias='reached-max-com-off'
    )


class Asset(BaseModel):
    all_properties: Optional[List[AllProperty]] = Field(None, alias='all-properties')
    assetID: Optional[int] = None
    assetTitle: Optional[str] = None
    assetURL: Optional[str] = None
    createDate: Optional[str] = None
    labels: Optional[List[Dict[str, Any]]] = None
    properties: Optional[Properties] = None
    source: Optional[str] = None
    taxonomy: Optional[str] = None
    text: Optional[List[Dict[str, Any]]] = None
    updateDate: Optional[str] = None
    vendorID: Optional[str] = None


class Comment(BaseModel):
    approveDate: Optional[str] = None
    asset: Optional[Asset] = None
    assetID: Optional[int] = None
    commentBody: Optional[str] = None
    commentID: Optional[int] = None
    commentSequence: Optional[int] = None
    commentTitle: Optional[str] = None
    commentType: Optional[str] = None
    createDate: Optional[str] = None
    display_name: Optional[str] = None
    editorsSelection: Optional[int] = None
    location: Optional[str] = None
    parentID: Optional[Any] = None
    recommendationCount: Optional[int] = None
    replies: Optional[List[Dict[str, Any]]] = None
    status: Optional[str] = None
    statusID: Optional[int] = None
    updateDate: Optional[str] = None
    userDisplayName: Optional[str] = None
    userID: Optional[int] = None
    userLocation: Optional[str] = None
    userTitle: Optional[str] = None
    userURL: Optional[str] = None


class Results(BaseModel):
    api_timestamp: Optional[str] = None
    comments: Optional[List[Comment]] = None
    totalCommentsReturned: Optional[int] = None


class JsonGetResponse(BaseModel):
    copyright: Optional[str] = None
    debug: Optional[Debug] = None
    results: Optional[Results] = None
    status: Optional[str] = None
