# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T07:44:07+00:00

from __future__ import annotations

from typing import Any, List, Optional

from pydantic import BaseModel


class Debug(BaseModel):
    version: Optional[float] = None


class Comment(BaseModel):
    approveDate: Optional[str] = None
    commentBody: Optional[str] = None
    commentID: Optional[int] = None
    commentSequence: Optional[int] = None
    commentTitle: Optional[str] = None
    commentType: Optional[str] = None
    createDate: Optional[str] = None
    depth: Optional[int] = None
    editorsSelection: Optional[bool] = None
    parentID: Optional[Any] = None
    parentUserDisplayName: Optional[Any] = None
    permID: Optional[str] = None
    picURL: Optional[str] = None
    recommendations: Optional[int] = None
    recommendedFlag: Optional[Any] = None
    replies: Optional[List] = None
    replyCount: Optional[int] = None
    reportAbuseFlag: Optional[Any] = None
    sharing: Optional[int] = None
    status: Optional[str] = None
    timespeople: Optional[int] = None
    trusted: Optional[int] = None
    updateDate: Optional[str] = None
    userDisplayName: Optional[str] = None
    userID: Optional[int] = None
    userLocation: Optional[str] = None
    userTitle: Optional[Any] = None
    userURL: Optional[Any] = None


class Results(BaseModel):
    api_timestamp: Optional[str] = None
    callerID: Optional[Any] = None
    comments: Optional[List[Comment]] = None
    depthLimit: Optional[int] = None
    filter: Optional[str] = None
    page: Optional[int] = None
    replyLimit: Optional[int] = None
    sort: Optional[str] = None
    totalCommentsFound: Optional[int] = None
    totalCommentsReturned: Optional[int] = None
    totalEditorsSelectionFound: Optional[int] = None
    totalEditorsSelectionReturned: Optional[int] = None
    totalParentCommentsFound: Optional[int] = None
    totalParentCommentsReturned: Optional[int] = None
    totalRecommendationsFound: Optional[int] = None
    totalRecommendationsReturned: Optional[int] = None
    totalReplyCommentsFound: Optional[int] = None
    totalReplyCommentsReturned: Optional[int] = None
    totalReporterReplyCommentsFound: Optional[int] = None
    totalReporterReplyCommentsReturned: Optional[int] = None


class JsonGetResponse(BaseModel):
    copyright: Optional[str] = None
    debug: Optional[Debug] = None
    results: Optional[Results] = None
    status: Optional[str] = None
