# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T07:44:07+00:00



import argparse
import json
import os
from typing import *
from typing import Optional

from autogen.mcp.mcp_proxy import MCPProxy
from autogen.mcp.mcp_proxy.security import APIKeyQuery, BaseSecurity
from fastapi import Query

from models.User_contentBy_date import JsonGetResponse
from models.User_contentRecent import JsonGetResponse
from models.User_contentUrl import JsonGetResponse
from models.User_contentUser import JsonGetResponse

app = MCPProxy(
    description='Get access to comments from registered users on New York Times articles.  NOTE: This API is deprecated.',
    termsOfService='http://developer.nytimes.com/tou',
    title='Community API',
    version='3.0.0',
    servers=[{'url': 'http://api.nytimes.com/svc/community/v3'}],
)


@app.get(
    '/user-content/by-date.json',
    tags=['user_comment_retrieval'],
    security=[
        APIKeyQuery(name="api-key"),
    ],
)
def g_e_t_user_content_by_date_json(date: Optional[str] = None):
    """
    Comments by Date
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/user-content/recent.json',
    tags=['user_comment_retrieval'],
    security=[
        APIKeyQuery(name="api-key"),
    ],
)
def g_e_t_user_content_recent_json():
    """
    Recent User Comments
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/user-content/url.json',
    tags=['user_comment_retrieval'],
    security=[
        APIKeyQuery(name="api-key"),
    ],
)
def g_e_t_user_content_url_json(url: Optional[str] = None):
    """
    Comments by URL
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/user-content/user.json',
    tags=['user_comment_retrieval'],
    security=[
        APIKeyQuery(name="api-key"),
    ],
)
def g_e_t_user_content_user_json(user_i_d: Optional[int] = Query(None, alias='userID')):
    """
    Comments by User
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="MCP Server")
    parser.add_argument(
        "transport",
        choices=["stdio", "sse", "streamable-http"],
        help="Transport mode (stdio, sse or streamable-http)",
    )
    args = parser.parse_args()

    if "CONFIG_PATH" in os.environ:
        config_path = os.environ["CONFIG_PATH"]
        app.load_configuration(config_path)

    if "CONFIG" in os.environ:
        config = os.environ["CONFIG"]
        app.load_configuration_from_string(config)

    if "SECURITY" in os.environ:
        security_params = BaseSecurity.parse_security_parameters_from_env(
            os.environ,
        )

        app.set_security_params(security_params)

    mcp_settings = json.loads(os.environ.get("MCP_SETTINGS", "{}"))

    app.get_mcp(**mcp_settings).run(transport=args.transport)
